version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    networks:
      - app-network

networks:
  app-network:
